<RockSimDocument>
<FileVersion>4</FileVersion>
<DesignInformation>
<RocketDesign>
<Name>Black Brant II</Name>
<CalculateCD>1</CalculateCD>
<ProCalculateCD>1</ProCalculateCD>
<ProCalculateCN>1</ProCalculateCN>
<FixedCd>0.75</FixedCd>
<FixedCd2>0.8</FixedCd2>
<FixedCd3>0.81</FixedCd3>
<FixedCd2Alone>0.95</FixedCd2Alone>
<FixedCd3Alone>0.95</FixedCd3Alone>
<StageCount>1</StageCount>
<Stage3Mass>10720.</Stage3Mass>
<Stage2Mass>0.</Stage2Mass>
<Stage1Mass>0.</Stage1Mass>
<Stage321CG>0.</Stage321CG>
<Stage32CG>0.</Stage32CG>
<Stage3CG>1660.</Stage3CG>
<Stage2CGAlone>0.</Stage2CGAlone>
<Stage1CGAlone>0.</Stage1CGAlone>
<CPCalcFlags>4</CPCalcFlags>
<LaunchGuideLength>914.4</LaunchGuideLength>
<UseKnownMass>1</UseKnownMass>
<DefaultFinish>0</DefaultFinish>
<FinishMedium>0</FinishMedium>
<FinishCoatCount>1</FinishCoatCount>
<GlueType>0</GlueType>
<CPSimFlags>4</CPSimFlags>
<LastSerialNumber>22</LastSerialNumber>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<CameraState>CSV1|1|1091.64,0,0|1091.64,-7089.55,15203.6|2.46331e-16,-0.984808,0.173648|10583.6,24609.9|30|2|16775.3|180|0|0|0|0</CameraState>
<BarromanXN>0,2400.02,0,0</BarromanXN>
<BarrowmanCNa>0,28.8417,0,0</BarrowmanCNa>
<RockSimXN>0,2448.38,0,0</RockSimXN>
<RockSimCNa>0,40.9352,0,0</RockSimCNa>
<RockSimCNa90>0,0,0,0</RockSimCNa90>
<RockSimXN90>0,0,0,0</RockSimXN90>
<ViewType>0</ViewType>
<ViewStageCount>1</ViewStageCount>
<ViewTypeEdit>0</ViewTypeEdit>
<ViewStageCountEdit>1</ViewStageCountEdit>
<ZoomFactor>0.</ZoomFactor>
<ZoomFactorEdit>0.</ZoomFactorEdit>
<ScrollPosX>0</ScrollPosX>
<ScrollPosY>0</ScrollPosY>
<ScrollPosXEdit>0</ScrollPosXEdit>
<ScrollPosYEdit>0</ScrollPosYEdit>
<ThreeDFlags>0</ThreeDFlags>
<ThreeDFlagsEdit>0</ThreeDFlagsEdit>
<UseModelSprite>1</UseModelSprite>
<SpritePath>/Users/ron/SynologyDrive/Rockets/fleet/Madcow_BlackBrant_5.5in</SpritePath>
<SpritePrefix>bb</SpritePrefix>
<StaticMarginRef>0</StaticMarginRef>
<UserRefDiameter>0.</UserRefDiameter>
<SideMarkerHeight>10.</SideMarkerHeight>
<SideDimensionHeight>10.</SideDimensionHeight>
<BaseMarkerHeight>10.</BaseMarkerHeight>
<BaseDimensionHeight>10.</BaseDimensionHeight>
<ShowGlideCP>0</ShowGlideCP>
<ShowGridTypeSide>0</ShowGridTypeSide>
<ShowGridTypeBase>0</ShowGridTypeBase>
<GridSpacing>10.</GridSpacing>
<GridOpacity>0.15</GridOpacity>
<GridColor>black</GridColor>
<MaxDiaWithFins>766.971</MaxDiaWithFins>
<MaxDiaWithoutFins>140.</MaxDiaWithoutFins>
<MaxLenWithFins>2807.</MaxLenWithFins>
<MaxLenWithoutFins>2737.</MaxLenWithoutFins>
<MinXExtent>0.</MinXExtent>
<MaxXExtent>2807.</MaxXExtent>
<CalculatedMaxStageDia>0,140,0,0</CalculatedMaxStageDia>
<CalculatedStageLen>0,2737,0,0</CalculatedStageLen>
<Cd3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd3>
<Cd32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd32>
<Cd321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd321>
<Cb3>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb3>
<Cb32>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb32>
<Cb321>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb321>
<CNa3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa3>
<CNa32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa32>
<CNa321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa321>
<CP3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP3>
<CP32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP32>
<CP321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP321>
<SimulationEventList>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.801</DeployedAt_Altitude>
<DeployedAt_Velocity>32.6223</DeployedAt_Velocity>
<DeployedAt_Range>-105.112</DeployedAt_Range>
<DeployedAt_Time>44.7625</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>1132.42</DeployedAt_Altitude>
<DeployedAt_Velocity>9.62047</DeployedAt_Velocity>
<DeployedAt_Range>-146.395</DeployedAt_Range>
<DeployedAt_Time>15.68</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEventList>
<Stage3Parts>
<NoseCone>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>1230.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Nose cone</Name>
<KnownCG>630.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>68.0459</CalcMass>
<CalcCG>652.861</CalcCG>
<WettedSurface>0.167942</WettedSurface>
<PaintedSurface>0.167942</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,255,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>6</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>2.</BarrowmanCNa>
<BarrowmanXN>0.507492</BarrowmanXN>
<RockSimCNa>2.</RockSimCNa>
<RockSimXN>0.507492</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>0.</Station>
<Len>762.</Len>
<BaseDia>140.</BaseDia>
<FinishCode>0</FinishCode>
<ShapeCode>0</ShapeCode>
<ConstructionType>1</ConstructionType>
<ShoulderLen>148.</ShoulderLen>
<WallThickness>2.</WallThickness>
<ShapeParameter>0.</ShapeParameter>
<ShoulderOD>136.</ShoulderOD>
<BaseExtensionLen>60.</BaseExtensionLen>
<CoreDia>0.</CoreDia>
<CoreLen>0.</CoreLen>
<AttachedParts>
</AttachedParts>
</NoseCone>
<BodyTube>
<PartMfg>Madcow Rocketry</PartMfg>
<KnownMass>891.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Upper Airframe</Name>
<KnownCG>255.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>56.6684</CalcMass>
<CalcCG>255.</CalcCG>
<WettedSurface>0.22431</WettedSurface>
<PaintedSurface>0.22431</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>5</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>822.</Station>
<OD>140.</OD>
<ID>136.</ID>
<Len>510.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Parachute>
<PartMfg>Fruity Chutes</PartMfg>
<KnownMass>380.</KnownMass>
<Density>0.006685</Density>
<Material>Rip stop nylon</Material>
<Name><![CDATA[Main (72")]]></Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-50.</Xb>
<CalcMass>214.306</CalcMass>
<CalcCG>152.4</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>1</DensityType>
<PartNo>29183</PartNo>
<PartDesc><![CDATA[72" Nylon Toroidal]]></PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>10</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>772.</Station>
<Dia>1828.8</Dia>
<SpillHoleDia>0.</SpillHoleDia>
<SideCount>0</SideCount>
<ShroudLineCount>18</ShroudLineCount>
<Thickness>0.76</Thickness>
<ShroudLineLen>2108.2</ShroudLineLen>
<ChuteCount>1</ChuteCount>
<ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
<ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
<DragCoefficient>0.75</DragCoefficient>
<AttachedParts>
</AttachedParts>
</Parachute>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>Madcow Rocketry</PartMfg>
<KnownMass>86.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Switch Band</Name>
<KnownCG>25.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>5.55573</CalcMass>
<CalcCG>25.</CalcCG>
<WettedSurface>0.0219911</WettedSurface>
<PaintedSurface>0.0219911</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>3</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1332.</Station>
<OD>140.</OD>
<ID>136.</ID>
<Len>50.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>733.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Payload Bay</Name>
<KnownCG>178.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-153.</Xb>
<CalcMass>451.348</CalcMass>
<CalcCG>178.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>4</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,255,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1179.</Station>
<OD>136.</OD>
<ID>130.6</ID>
<Len>356.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>253.</KnownMass>
<Density>344.269</Density>
<Material>1/4 Aircraft Plywood</Material>
<Name>Forward Bulkhead</Name>
<KnownCG>3.4</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>31.3605</CalcMass>
<CalcCG>3.4</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>15</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1179.</Station>
<OD>130.6</OD>
<ID>0.</ID>
<Len>6.8</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>253.</KnownMass>
<Density>344.269</Density>
<Material>1/4 Aircraft Plywood</Material>
<Name>Aft Bulkhead</Name>
<KnownCG>3.4</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>31.3605</CalcMass>
<CalcCG>3.4</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>17</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1528.2</Station>
<OD>130.6</OD>
<ID>0.</ID>
<Len>6.8</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
</AttachedParts>
</BodyTube>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>Madcow Rocketry</PartMfg>
<KnownMass>2097.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Lower Airframe</Name>
<KnownCG>611.5</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>135.893</CalcMass>
<CalcCG>611.5</CalcCG>
<WettedSurface>0.537903</WettedSurface>
<PaintedSurface>0.537903</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>10625</PartNo>
<PartDesc>3??? x 48??? Fiberglass Tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>2</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1382.</Station>
<OD>140.</OD>
<ID>136.</ID>
<Len>1223.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>234.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Motor Mount</Name>
<KnownCG>207.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-90.</Xb>
<CalcMass>19.2506</CalcMass>
<CalcCG>207.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>7</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(170,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2281.</Station>
<OD>78.5</OD>
<ID>75.5</ID>
<Len>414.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>1</IsMotorMount>
<MotorDia>75.</MotorDia>
<EngineOverhang>12.7</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
</AttachedParts>
</BodyTube>
<CustomFinSet>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>1734.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Fin set</Name>
<KnownCG>260.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>985.</Xb>
<CalcMass>152.022</CalcMass>
<CalcCG>241.189</CalcCG>
<WettedSurface>0.184187</WettedSurface>
<PaintedSurface>0.552561</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>9</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>27.1437</BarrowmanCNa>
<BarrowmanXN>2.54226</BarrowmanXN>
<RockSimCNa>39.2371</RockSimCNa>
<RockSimXN>2.54888</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2367.</Station>
<FinCount>3</FinCount>
<RootChord>370.</RootChord>
<TipChord>212.18</TipChord>
<SemiSpan>308.</SemiSpan>
<MidChordLen>339.367</MidChordLen>
<SweepDistance>221.41</SweepDistance>
<Thickness>4.</Thickness>
<ShapeCode>2</ShapeCode>
<FinishCode>0</FinishCode>
<TipShapeCode>2</TipShapeCode>
<TabLength>220.</TabLength>
<TabDepth>30.75</TabDepth>
<TabOffset>0.</TabOffset>
<SweepMode>1</SweepMode>
<SweepAngle>0.</SweepAngle>
<RockSimXNPerFin>0.</RockSimXNPerFin>
<RockSimRadialXNPerFin>212.579</RockSimRadialXNPerFin>
<RockSimCNaPerFin>22.6536</RockSimCNaPerFin>
<TaperRatio>0.573459</TaperRatio>
<CantAngle>0.</CantAngle>
<CantPivotPoint>0.</CantPivotPoint>
<AverageChord>297.5</AverageChord>
<EffectiveTipChord>212.18</EffectiveTipChord>
<PointList>370,0|440,308|215,308|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|</PointList>
<AutoCalcGridStepX>0,0,0,0,0,0,0</AutoCalcGridStepX>
<GridStepCountX>10,10,10,10,10,10,10</GridStepCountX>
<UseAbsoluteGridStepsX>0,0,0,0,0,0,0</UseAbsoluteGridStepsX>
<GridStepSizeX>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeX>
<SnapToSizeX>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeX>
<AutoCalcGridStepY>0,0,0,0,0,0,0</AutoCalcGridStepY>
<GridStepCountY>10,10,10,10,10,10,10</GridStepCountY>
<UseAbsoluteGridStepsY>0,0,0,0,0,0,0</UseAbsoluteGridStepsY>
<GridStepSizeY>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeY>
<SnapToSizeY>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeY>
<AttachedParts>
</AttachedParts>
</CustomFinSet>
<Parachute>
<PartMfg>Apogee</PartMfg>
<KnownMass>16.9</KnownMass>
<Density>0.006685</Density>
<Material>Rip stop nylon</Material>
<Name><![CDATA[Drogue (24")]]></Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>311.3</Xb>
<CalcMass>17.3415</CalcMass>
<CalcCG>50.8</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>1</DensityType>
<PartNo>29093</PartNo>
<PartDesc><![CDATA[24" Nylon Hexagon]]></PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>11</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1693.3</Station>
<Dia>609.6</Dia>
<SpillHoleDia>0.</SpillHoleDia>
<SideCount>6</SideCount>
<ShroudLineCount>6</ShroudLineCount>
<Thickness>0.76</Thickness>
<ShroudLineLen>609.6</ShroudLineLen>
<ChuteCount>1</ChuteCount>
<ShroudLineMassPerMM>0.00032972</ShroudLineMassPerMM>
<ShroudLineMaterial>Carpet String (Apogee 29500)</ShroudLineMaterial>
<DragCoefficient>0.75</DragCoefficient>
<AttachedParts>
</AttachedParts>
</Parachute>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>62.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Fwd Centering ring</Name>
<KnownCG>1.5</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>240.</Xb>
<CalcMass>22.333</CalcMass>
<CalcCG>1.59</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>19</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2361.82</Station>
<OD>136.</OD>
<ID>78.5</ID>
<Len>3.18</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>62.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Aft Centering ring</Name>
<KnownCG>1.5</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>14.</Xb>
<CalcMass>22.333</CalcMass>
<CalcCG>1.59</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>20</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2587.82</Station>
<OD>136.</OD>
<ID>78.5</ID>
<Len>3.18</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
</AttachedParts>
</BodyTube>
<Transition>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>1.65</KnownMass>
<Density>1049.21</Density>
<Material>Polystyrene PS</Material>
<Name>Boattail</Name>
<KnownCG>47.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>162.16</CalcMass>
<CalcCG>46.3851</CalcCG>
<WettedSurface>0.039787</WettedSurface>
<PaintedSurface>0.039787</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>rgb(255,255,0)</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>13</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>-0.301955</BarrowmanCNa>
<BarrowmanXN>2.65136</BarrowmanXN>
<RockSimCNa>-0.301955</RockSimCNa>
<RockSimXN>2.65136</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2605.</Station>
<FrontDia>140.</FrontDia>
<RearDia>129.</RearDia>
<Len>94.</Len>
<FinishCode>0</FinishCode>
<FrontShoulderLen>0.</FrontShoulderLen>
<RearShoulderLen>0.</RearShoulderLen>
<ConstructionType>1</ConstructionType>
<WallThickness>4.</WallThickness>
<FrontShoulderDia>0.</FrontShoulderDia>
<RearShoulderDia>0.</RearShoulderDia>
<CoreDia>0.</CoreDia>
<ShapeCode>0</ShapeCode>
<ShapeParameter>0.</ShapeParameter>
<EquivNoseLen>1196.3</EquivNoseLen>
<EquivNoseOffset>1102.3</EquivNoseOffset>
<AttachedParts>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>65.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Tail Coupler</Name>
<KnownCG>17.5</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-8.</Xb>
<CalcMass>5.07135</CalcMass>
<CalcCG>17.5</CalcCG>
<WettedSurface>0.014954</WettedSurface>
<PaintedSurface>0.014954</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>14</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(85,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2597.</Station>
<OD>136.</OD>
<ID>130.6</ID>
<Len>35.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
</AttachedParts>
</BodyTube>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>205.</KnownMass>
<Density>0.</Density>
<Name>Thrust Plate</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>21</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2699.</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<MassObject>
<PartMfg>AeroPack</PartMfg>
<KnownMass>140.3</KnownMass>
<Density>0.</Density>
<Material>Aluminum</Material>
<Name>75mm AeroPack Retainer</Name>
<KnownCG>-20.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-20.</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>24121</PartNo>
<PartDesc>75mm AeroPack Retainer</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>22</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2719.</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</Transition>
</Stage3Parts>
<Stage2Parts>
</Stage2Parts>
<Stage1Parts>
</Stage1Parts>
<SideViewDims>
</SideViewDims>
<BaseViewDims>
</BaseViewDims>
<VertViewDims>
</VertViewDims>
</RocketDesign>
</DesignInformation>
<SimulationResultsList>
<SimulationResults>
<MaxAltitude>1132.42</MaxAltitude>
<MaxVelocity>147.075</MaxVelocity>
<MaxAcceleration>72.5845</MaxAcceleration>
<TimeToApogee>15.68</TimeToApogee>
<OptimalDelay>12.0863</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>140.408</VelocityAtDeplyment>
<AltitudeAtDeployment>354.56</AltitudeAtDeployment>
<DelayTime>0</DelayTime>
<EjectTime>3.59375</EjectTime>
<FinalState>2</FinalState>
<TimeToBurnout>3.59375</TimeToBurnout>
<TimeToLanding>68.8787</TimeToLanding>
<TimeToEject>3.59375</TimeToEject>
<MinLaunchGuideLen>1.31545</MinLaunchGuideLen>
<MaxVertVelocity>146.563</MaxVertVelocity>
<MaxHorzVelocity>2.20826</MaxHorzVelocity>
<MaxVertAcceleration>97.4788</MaxVertAcceleration>
<MaxHorzAcceleration>0.522869</MaxHorzAcceleration>
<MaxRange>146.395</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2000.</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34111</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.5316</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>4</LaunchCloudCoverPreset>
<LaunchCCLow>0.1</LaunchCCLow>
<LaunchCCHigh>0.3</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99937</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[K700W-0] </SimulationName>
<VelocityAtLaunchGuideEnd>16.7758</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.2775</TimeToFreeFlight>
<TimeToMaxVelocity>2.91125</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.63125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
<ExecutionTime>0.548</ExecutionTime>
<RangeAtLanding>-62.5645</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>9.98793</VelocityAtLanding>
<XVelcoityAtLanding>2.20831</XVelcoityAtLanding>
<YVelocityAtLanding>-9.74075</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,3.59375,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,15.68,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>12755.3</Mass0>
<CG0>1779.91</CG0>
<LaterialMOI0>4.40842e+7</LaterialMOI0>
<RadialMOI0>0.0776386</RadialMOI0>
<CP0>2448.38</CP0>
<CNA0>40.9352</CNA0>
<SM0>4.77479</SM0>
<GUID>{89f80d9d-2525-49a2-9659-806d16a7e680}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>12.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>0</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>1</NinetyDegDanger>
<VelocityGuideSafe>1</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>1</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.801</DeployedAt_Altitude>
<DeployedAt_Velocity>32.6223</DeployedAt_Velocity>
<DeployedAt_Range>-105.112</DeployedAt_Range>
<DeployedAt_Time>44.7625</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>1132.42</DeployedAt_Altitude>
<DeployedAt_Velocity>9.62047</DeployedAt_Velocity>
<DeployedAt_Range>-146.395</DeployedAt_Range>
<DeployedAt_Time>15.68</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>K700W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.5</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>0.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>801.339</MaxAltitude>
<MaxVelocity>124.941</MaxVelocity>
<MaxAcceleration>59.6229</MaxAcceleration>
<TimeToApogee>13.6325</TimeToApogee>
<OptimalDelay>10.8013</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>122.409</VelocityAtDeplyment>
<AltitudeAtDeployment>189.756</AltitudeAtDeployment>
<DelayTime>0</DelayTime>
<EjectTime>2.83125</EjectTime>
<FinalState>1</FinalState>
<TimeToBurnout>2.83125</TimeToBurnout>
<TimeToLanding>56.0587</TimeToLanding>
<TimeToEject>2.83125</TimeToEject>
<MinLaunchGuideLen>2.31353</MinLaunchGuideLen>
<MaxVertVelocity>123.294</MaxVertVelocity>
<MaxHorzVelocity>3.52276</MaxHorzVelocity>
<MaxVertAcceleration>97.4982</MaxVertAcceleration>
<MaxHorzAcceleration>0.735157</MaxHorzAcceleration>
<MaxRange>206.008</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2000.</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34111</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.5316</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>4</LaunchCloudCoverPreset>
<LaunchCCLow>0.1</LaunchCCLow>
<LaunchCCHigh>0.3</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99932</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[K735SK-0] </SimulationName>
<VelocityAtLaunchGuideEnd>12.4544</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.3525</TimeToFreeFlight>
<TimeToMaxVelocity>2.595</TimeToMaxVelocity>
<TimeToMaxAcceleration>1.36125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
<ExecutionTime>0.151</ExecutionTime>
<RangeAtLanding>-79.608</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>10.3033</VelocityAtLanding>
<XVelcoityAtLanding>2.1618</XVelcoityAtLanding>
<YVelocityAtLanding>-10.074</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,2.83125,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,13.6325,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>13228.8</Mass0>
<CG0>1823.19</CG0>
<LaterialMOI0>4.78256e+7</LaterialMOI0>
<RadialMOI0>0.0564414</RadialMOI0>
<CP0>2448.38</CP0>
<CNA0>40.9352</CNA0>
<SM0>4.46565</SM0>
<GUID>{f1d14796-811a-40f3-b71a-3d20bcb6fc7d}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>10.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>1</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>-1</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>1</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.809</DeployedAt_Altitude>
<DeployedAt_Velocity>33.5037</DeployedAt_Velocity>
<DeployedAt_Range>-142.255</DeployedAt_Range>
<DeployedAt_Time>32.5387</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>801.339</DeployedAt_Altitude>
<DeployedAt_Velocity>16.5213</DeployedAt_Velocity>
<DeployedAt_Range>-206.008</DeployedAt_Range>
<DeployedAt_Time>13.6325</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>K735SK</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Cesaroni Technology Inc.</EngineMfg>
<EngineOverhang>0.5</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>0.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>904.789</MaxAltitude>
<MaxVelocity>131.403</MaxVelocity>
<MaxAcceleration>63.6655</MaxAcceleration>
<TimeToApogee>14.3325</TimeToApogee>
<OptimalDelay>11.2425</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>129.089</VelocityAtDeplyment>
<AltitudeAtDeployment>237.104</AltitudeAtDeployment>
<DelayTime>0</DelayTime>
<EjectTime>3.09</EjectTime>
<FinalState>1</FinalState>
<TimeToBurnout>3.09</TimeToBurnout>
<TimeToLanding>60.7887</TimeToLanding>
<TimeToEject>3.09</TimeToEject>
<MinLaunchGuideLen>1.83395</MinLaunchGuideLen>
<MaxVertVelocity>130.079</MaxVertVelocity>
<MaxHorzVelocity>3.5316</MaxHorzVelocity>
<MaxVertAcceleration>97.4778</MaxVertAcceleration>
<MaxHorzAcceleration>0.741318</MaxHorzAcceleration>
<MaxRange>197.79</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2000.</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>3</LaunchWindPreset>
<LaunchWindLowSpeed>1.34111</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.5316</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>4</LaunchCloudCoverPreset>
<LaunchCCLow>0.1</LaunchCCLow>
<LaunchCCHigh>0.3</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99932</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[K675SK-0] </SimulationName>
<VelocityAtLaunchGuideEnd>14.1215</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.305</TimeToFreeFlight>
<TimeToMaxVelocity>2.85625</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.025</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
<ExecutionTime>0.462</ExecutionTime>
<RangeAtLanding>-47.6785</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>10.0586</VelocityAtLanding>
<XVelcoityAtLanding>2.51451</XVelcoityAtLanding>
<YVelocityAtLanding>-9.73918</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,3.09,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,14.3325,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>12660.</Mass0>
<CG0>1774.85</CG0>
<LaterialMOI0>4.35344e+7</LaterialMOI0>
<RadialMOI0>0.0762444</RadialMOI0>
<CP0>2448.38</CP0>
<CNA0>40.9352</CNA0>
<SM0>4.81092</SM0>
<GUID>{e3b19d13-92aa-4c06-b430-ac9d61695c70}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>11.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>2</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>1</NinetyDegDanger>
<VelocityGuideSafe>1</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>1</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.824</DeployedAt_Altitude>
<DeployedAt_Velocity>32.7605</DeployedAt_Velocity>
<DeployedAt_Range>-119.812</DeployedAt_Range>
<DeployedAt_Time>36.6662</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>904.789</DeployedAt_Altitude>
<DeployedAt_Velocity>14.8848</DeployedAt_Velocity>
<DeployedAt_Range>-197.79</DeployedAt_Range>
<DeployedAt_Time>14.3325</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>K675SK</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Cesaroni Technology Inc.</EngineMfg>
<EngineOverhang>0.5</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>0.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>2883.97</MaxAltitude>
<MaxVelocity>274.848</MaxVelocity>
<MaxAcceleration>104.069</MaxAcceleration>
<TimeToApogee>23.69</TimeToApogee>
<OptimalDelay>19.2</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>1</FinalState>
<TimeToBurnout>4.49</TimeToBurnout>
<TimeToLanding>121.289</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>1.02212</MinLaunchGuideLen>
<MaxVertVelocity>274.697</MaxVertVelocity>
<MaxHorzVelocity>0.718165</MaxHorzVelocity>
<MaxVertAcceleration>104.069</MaxVertAcceleration>
<MaxHorzAcceleration>0.604333</MaxHorzAcceleration>
<MaxRange>144.096</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.894081</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99946</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[L1115CL-P] </SimulationName>
<VelocityAtLaunchGuideEnd>12.7787</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.21125</TimeToFreeFlight>
<TimeToMaxVelocity>4.15875</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.18</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
<ExecutionTime>0.344</ExecutionTime>
<RangeAtLanding>-120.459</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>10.29</VelocityAtLanding>
<XVelcoityAtLanding>0.718183</XVelcoityAtLanding>
<YVelocityAtLanding>-10.2649</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,23.69,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>15124.</Mass0>
<CG0>1871.11</CG0>
<LaterialMOI0>5.69954e+7</LaterialMOI0>
<RadialMOI0>0.144467</RadialMOI0>
<CP0>2448.38</CP0>
<CNA0>40.9352</CNA0>
<SM0>4.12334</SM0>
<GUID>{6268eb24-356a-4278-ab73-062dcafa6397}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>19.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>3</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>-1</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>1</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.825</DeployedAt_Altitude>
<DeployedAt_Velocity>34.3557</DeployedAt_Velocity>
<DeployedAt_Range>-132.568</DeployedAt_Range>
<DeployedAt_Time>98.4825</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>2883.97</DeployedAt_Altitude>
<DeployedAt_Velocity>5.45154</DeployedAt_Velocity>
<DeployedAt_Range>-144.096</DeployedAt_Range>
<DeployedAt_Time>23.69</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>L1115CL</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Cesaroni Technology Inc.</EngineMfg>
<EngineOverhang>0.5</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>2104.01</MaxAltitude>
<MaxVelocity>227.864</MaxVelocity>
<MaxAcceleration>77.6057</MaxAcceleration>
<TimeToApogee>20.665</TimeToApogee>
<OptimalDelay>16.9337</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>1</FinalState>
<TimeToBurnout>3.73125</TimeToBurnout>
<TimeToLanding>99.1337</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>1.37038</MinLaunchGuideLen>
<MaxVertVelocity>227.864</MaxVertVelocity>
<MaxHorzVelocity>0.894081</MaxHorzVelocity>
<MaxVertAcceleration>97.5205</MaxVertAcceleration>
<MaxHorzAcceleration>0.00569888</MaxHorzAcceleration>
<MaxRange>46.1295</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.894081</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99943</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[L1050BS-P] </SimulationName>
<VelocityAtLaunchGuideEnd>10.9699</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.19875</TimeToFreeFlight>
<TimeToMaxVelocity>3.45125</TimeToMaxVelocity>
<TimeToMaxAcceleration>1.125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
<ExecutionTime>0.279</ExecutionTime>
<RangeAtLanding>46.1295</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>10.1249</VelocityAtLanding>
<XVelcoityAtLanding>0.818767</XVelcoityAtLanding>
<YVelocityAtLanding>-10.0917</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,20.665,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>14167.7</Mass0>
<CG0>1852.85</CG0>
<LaterialMOI0>5.26117e+7</LaterialMOI0>
<RadialMOI0>0.0886417</RadialMOI0>
<CP0>2448.38</CP0>
<CNA0>40.9352</CNA0>
<SM0>4.25377</SM0>
<GUID>{de7e10de-3374-4db3-8526-2ee89d83c895}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>16.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>4</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>-1</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>1</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.833</DeployedAt_Altitude>
<DeployedAt_Velocity>33.7827</DeployedAt_Velocity>
<DeployedAt_Range>25.8102</DeployedAt_Range>
<DeployedAt_Time>75.9075</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>2104.01</DeployedAt_Altitude>
<DeployedAt_Velocity>0.0620718</DeployedAt_Velocity>
<DeployedAt_Range>-1.39228</DeployedAt_Range>
<DeployedAt_Time>20.665</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>L1050BS</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Cesaroni Technology Inc.</EngineMfg>
<EngineOverhang>0.5</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>1149.83</MaxAltitude>
<MaxVelocity>148.635</MaxVelocity>
<MaxAcceleration>48.5368</MaxAcceleration>
<TimeToApogee>16.36</TimeToApogee>
<OptimalDelay>12.5613</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>1</FinalState>
<TimeToBurnout>3.79875</TimeToBurnout>
<TimeToLanding>68.9625</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>2.31899</MinLaunchGuideLen>
<MaxVertVelocity>148.42</MaxVertVelocity>
<MaxHorzVelocity>0.894081</MaxHorzVelocity>
<MaxVertAcceleration>97.5046</MaxVertAcceleration>
<MaxHorzAcceleration>0.337531</MaxHorzAcceleration>
<MaxRange>97.4884</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.894081</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.9994</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[K661BS-P] </SimulationName>
<VelocityAtLaunchGuideEnd>8.35267</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.24375</TimeToFreeFlight>
<TimeToMaxVelocity>3.57875</TimeToMaxVelocity>
<TimeToMaxAcceleration>1.24125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
<ExecutionTime>0.206</ExecutionTime>
<RangeAtLanding>-64.2628</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>9.96247</VelocityAtLanding>
<XVelcoityAtLanding>0.221756</XVelcoityAtLanding>
<YVelocityAtLanding>-9.96</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,16.36,0,0</TimeToDeployment>
<DeploymentType>32,32,80,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>13247.8</Mass0>
<CG0>1824.19</CG0>
<LaterialMOI0>4.79412e+7</LaterialMOI0>
<RadialMOI0>0.0565961</RadialMOI0>
<CP0>2448.38</CP0>
<CNA0>40.9352</CNA0>
<SM0>4.4585</SM0>
<GUID>{aa79a1e4-70c0-4986-a17d-357df985019c}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>12.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>5</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>-1</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>1</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>0</ProEvent>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>10</PartSerialNo>
<Type>5</Type>
<DeployAltitude>243.84</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>243.837</DeployedAt_Altitude>
<DeployedAt_Velocity>33.3343</DeployedAt_Velocity>
<DeployedAt_Range>-74.214</DeployedAt_Range>
<DeployedAt_Time>45.4075</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,10,28</TestType>
<TestCondition>0,2,0</TestCondition>
<TestValueAltitude>0,91.44,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>4</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>1149.83</DeployedAt_Altitude>
<DeployedAt_Velocity>6.20294</DeployedAt_Velocity>
<DeployedAt_Range>-97.4884</DeployedAt_Range>
<DeployedAt_Time>16.36</DeployedAt_Time>
<DeviceID>128</DeviceID>
<TestType>4,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
<ProEvent>1</ProEvent>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>K661BS</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Cesaroni Technology Inc.</EngineMfg>
<EngineOverhang>0.5</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
</SimulationResultsList>
</RockSimDocument>
